apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: cloudos
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/anselmes/cloudos/releases/download/v0.1.0/cloudos_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./cloudos"
      to: "."
    - from: LICENSE
      to: "."
    bin: "cloudos"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/anselmes/cloudos/releases/download/v0.1.0/cloudos_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./cloudos"
      to: "."
    - from: LICENSE
      to: "."
    bin: "cloudos"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/anselmes/cloudos/releases/download/v0.1.0/cloudos_windows_amd64.zip
    sha256: ""
    files:
    - from: "/cloudos.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "cloudos.exe"
  shortDescription: A new plugin
  homepage: https://github.com/anselmes/cloudos
  caveats: |
    Usage:
      $ kubectl cloudos

    For additional options:
      $ kubectl cloudos --help
      or https://github.com/anselmes/cloudos/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
